services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    command: yarn dev
    restart: always
    networks:
      - "pocket"

networks:
  pocket:
    driver: bridge